Add `servers` component
Theseus-Aegis/Mods pull request #462
Opened 2020-10-14 23:15 UTC by JoramD0

**When merged this pull request will:**
- Add 2 main menu spotlight entries for the contracts and training servers (getting the password from CBA).

Note:
CBA only saves passwords entered in the server browser. That means that if someone joined through Swifty or entered the password after clicking the menu spotlight button it will not save the password for next time

2020-10-27 16:49 UTC, jonpas requested changes

2020-10-27 16:49 UTC, jonpas commented on addons/servers/$PBOPREFIX$
> +x\tac\addons\servers
```suggestion
x\tac\addons\servers

```

2020-10-27 16:49 UTC, jonpas commented on addons/servers/CfgMainMenuSpotlight.hpp
> +{
Opening bracket on same line!

2020-10-27 16:49 UTC, jonpas commented on addons/servers/CfgMainMenuSpotlight.hpp
> +        action = "private _passwordCache = profileNamespace getVariable ['cba_ui_ServerPasswords', [[], []]];  private _index = (_passwordCache select 0) find '213.239.214.39:2302';  private _passwor
Let's make this into a function. Can re-use same code for both servers then.

2020-10-28 22:48 UTC, jonpas requested changes

2020-10-28 22:48 UTC, jonpas commented on addons/servers/XEH_preInit.sqf
> +GVAR(vehiclesList) = [];
Remove those 3.

2020-10-28 22:48 UTC, jonpas commented on addons/servers/XEH_preInit.sqf
> +ADDON = true;
```suggestion
ADDON = true;

```

2020-10-28 22:48 UTC, jonpas commented on addons/servers/config.cpp
> +
```suggestion
```

2020-10-28 22:53 UTC, jonpas requested changes

2020-10-28 22:53 UTC, jonpas commented on addons/servers/functions/fnc_joinServer.sqf
> +
```suggestion
```

2020-10-28 22:53 UTC, jonpas commented on addons/servers/functions/fnc_joinServer.sqf
> +
```suggestion
```

2020-10-28 22:53 UTC, jonpas commented on addons/servers/CfgMainMenuSpotlight.hpp
> +{
Not done!

2020-10-28 22:55 UTC, jonpas approved these changes

2020-10-28 22:56 UTC, jonpas requested changes

2020-10-28 22:56 UTC, jonpas commented on addons/servers/CfgMainMenuSpotlight.hpp
> +    class JoinContractServer {
```suggestion
    class GVAR(joinContracts) {
```

2020-10-28 22:56 UTC, jonpas commented on addons/servers/CfgMainMenuSpotlight.hpp
> +    class JoinTrainingServer {
```suggestion
    class GVAR(joinTraining) {
```

2020-10-28 22:57 UTC, jonpas approved these changes

2020-11-06 07:23 UTC, jonpas commented
@JoramD0 tested latest?

2020-11-06 08:36 UTC, JoramD0 commented
Not yet, on my list for today

2020-11-06 09:42 UTC, JoramD0 commented
Looks like it is all working as intended

2020-11-06 10:00 UTC, jonpas approved these changes

2020-11-06 10:00 UTC, merged