Bodybag helper functions
Theseus-Aegis/Mods pull request #487
Opened 2021-03-12 20:45 UTC by JoramD0

**When merged this pull request will:**
- Add a function to get bodybag contents
- Add a function to create a new bodybag with contents from getter function

2021-03-12 20:59 UTC, jonpas requested changes

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/XEH_PREP.hpp
> +PREP(createBodybagBackkup)
```suggestion
PREP(createBodybagBackkup);
```

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/functions/fnc_createBodybagBackup.sqf
> +private _items = _bodybagContents select 0;
`params` instead of every `select` in this function (except inside loops).

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/functions/fnc_createBodybagBackup.sqf
> + * Create a bodybag filled with items from an array made by tac_bodybag_fnc_getBodybagContents.
```suggestion
 * Create a bodybag filled with items from an array returned by FUNC(getBodybagContents).
```

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/functions/fnc_createBodybagBackup.sqf
> + * 0: bodybagContents <ARRAY>
```suggestion
 * 0: Bodybag Contents <ARRAY>
```

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/functions/fnc_getBodybagContents.sqf
> + * Store a bodybag's contents in an array for later use with tac_bodybag_fnc_createBodybagBackup.
```suggestion
 * Returns a bodybag's contents in an array for use with FUNC(createBodybagBackup).
```

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/functions/fnc_getBodybagContents.sqf
> + * Bodybag contents array <ARRAY>
```suggestion
 * Bodybag Contents <ARRAY>
```

2021-03-12 20:59 UTC, jonpas commented on addons/bodybag/functions/fnc_getBodybagContents.sqf
> +_bodybagContents pushBack getItemCargo _object;
```suggestion
_bodybagContents pushBack (getItemCargo _object);
```
On all 4, keeps readability 100%.

2021-03-12 21:38 UTC, JoramD0 commented
Tested locally, no issues found

2021-03-12 22:09 UTC, jonpas commented on addons/bodybag/functions/fnc_createBodybagBackup.sqf
> +if (_bodybagContents isEqualTo [] || {count _bodybagContents isNotEqualTo 4}) exitWith {ERROR("Failed to create bodybag check inputted array");};
```suggestion
if (_bodybagContents isEqualTo [] || {(count _bodybagContents) isNotEqualTo 4}) exitWith {
    ERROR("Failed to create bodybag! Invalid input.");
};
```

2021-03-12 22:27 UTC, jonpas approved these changes

2021-03-15 23:12 UTC, jonpas approved these changes

2021-03-16 11:05 UTC, merged