MELB Tweaks - Rewrite scripts
Theseus-Aegis/Mods pull request #592
Opened 2023-06-14 18:19 UTC by jonpas

**When merged this pull request will:**
- **Rewrite all MELB scripts, optimize all code, remove dead code, move everything to scheduled environment**
  - Reduction of 4 scheduled loops to 1 unscheduled CBA PerFrameHandler
  - Network-optimized, at maximum 2x broadcast `setVariable` + 2x CBA Target Event each 0.1 seconds
- Remove post-processing effects on FLIR camera (in-optic gunner view)
- Use turret's vision mode to sync vision mode instead of the unit's personal vision mode (since v2.08, use with `RightCtrl+N`)
- Remove zoom transition on the MFDs (unnecessary delays, camera itself has no transition either)
- Rework zoom levels to be the same between FLIR camera and MFD views
- Disable old top HUD Radar _(replaced with new Sensor panels)_
- **Add Camera Ground Lock (GEOLOCK) and a HUD indicator**
- **Add BHOT TI capability and support**

2023-06-15 11:46 UTC, JoramD0 requested changes

2023-06-15 11:46 UTC, JoramD0 commented on optionals/melb_tweaks/functions/fnc_canToggleMFD.sqf
> + * Checks if MFD can be toggled (plaer in pilot or copilot seat).
```suggestion
 * Checks if MFD can be toggled (player in pilot or copilot seat).
```

2023-06-15 11:56 UTC, veteran29 commented on optionals/melb_tweaks/XEH_postInitClient.sqf
> +}] call CBA_fnc_addClassEventHandler;
Why not use `CBA_fnc_currentUnit` in these? Using `local` will cause issues with remote control and any zeus spawned units.

2023-06-16 11:08 UTC, JoramD0 approved these changes

2023-06-18 22:16 UTC, merged