Mission Autotest - Add AP Counter
Theseus-Aegis/Mods pull request #604
Opened 2023-07-30 22:18 UTC by Mike-MF

Surprisingly, it works, 6 is a warning, 10 is an error for now. Pretty much all AP units are coming out of TACU so I went with `isAP`

![Untitled](https://github.com/Theseus-Aegis/Mods/assets/29175040/ef6612ef-8cc6-49ef-8efa-34d5d7eccd3f)

2023-08-03 09:17 UTC, jonpas commented
If you're not sure about translations, best to remove them.

2023-08-03 20:48 UTC, Mike-MF commented
The translations should actually be pretty accurate.

2023-08-05 20:35 UTC, jonpas requested changes

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/functions/fnc_testAPAmount.sqf
> + * Tests AP AI amount
```suggestion
 * Tests AP AI amount.
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/functions/fnc_testAPAmount.sqf
> + * Author: TMF Team, Jonpas, Mike
```suggestion
 * Author: Mike
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/functions/fnc_testAPAmount.sqf
> +private _apAmount = count (allUnits select {(getNumber (configFile >> "CfgVehicles" >> typeOf _x >> "TACU_isAP")) == 1});
```suggestion
private _apAmount = count (allUnits select {
    getNumber (configFile >> "CfgVehicles" >> typeOf _x >> "TACU_isAP") == 1
});
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/functions/fnc_testAPCAmount.sqf
> + * Author: TMF Team, Jonpas, Mike
```suggestion
 * Author: Mike
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/functions/fnc_testGroupCount.sqf
> + * Author: TMF Team, Jonpas, Mike
```suggestion
 * Author: Mike
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/functions/fnc_testTankAmount.sqf
> + * Author: TMF Team, Jonpas, Mike
```suggestion
 * Author: Mike
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/stringtable.xml
> +            <English>Checks if the recommended amount of Wheeled APC vehicles are present.</English>
```suggestion
            <English>Checks if the recommended amount of Wheeled APCs are present.</English>
```

2023-08-05 20:35 UTC, jonpas commented on addons/mission_autotest/stringtable.xml
> +            <English>Checks if the recommended amount of Tracked vehicles are present.</English>
```suggestion
            <English>Checks if the recommended amount of Tracked Vehicles are present.</English>
```

2023-08-05 20:36 UTC, jonpas commented
"> 10 units in group" check should be added [here](https://github.com/Theseus-Aegis/Mods/blob/4cbc0498a7412ec8eba344f30ca45fc6905afa62/addons/mission_autotest/functions/fnc_testGroupSizes.sqf) instead, with every group that has more than 10 units being logged so it can be found.

2023-08-05 20:37 UTC, jonpas commented
Would also appreciate if Tank/Tracked APC/WheeledAPC can be streamlined between text and internal names.

2023-08-06 16:16 UTC, jonpas approved these changes

2023-08-06 16:16 UTC, merged